### PR TITLE
Responsive

### PR DESCRIPTION
**Pull request by G-Ray**

### CODE REVIEW

**Review by leventdem — APPROVED** [review]
OK.

**Review by sujeebant — COMMENTED** [review]
The modal does not seem to resize on window resize in Firefox/Chrome but it does resize when using the responsive tool in Firefox dev tools.

**Comment by G-Ray** [comment]
> The modal does not seem to resize on window resize in Firefox/Chrome but it does resize when using the responsive tool in Firefox dev tools.

Should be fixed now. I was comparing the device width. Now we check the width.

**Comment by sujeebant** [comment]
> > The modal does not seem to resize on window resize in Firefox/Chrome but it does resize when using the responsive tool in Firefox dev tools.
> 
> Should be fixed now. I was comparing the device width. Now we check the width.

:+1:

**Comment by sujeebant** [comment]
Should we have a minimum width under which the user would have to scroll instead of having an unreadable modal ?

**Pull request merged**
